services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: optigenius
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d optigenius"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pg_data:
